name: publish to github-pages

on:
  workflow_dispatch:
#  schedule:
#    - cron "12 * * * *"
  push:
    branches:
      - main

jobs:
  publish:
    name: build and deploy to GithubPages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://hanseartic.github.io/react_gh_pages

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: npm ci
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config user.name github-actions-bot
          git config user.email support+actions@github.com
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
